host: "![SxCtFjkZBjCB0rMJWRCnEQ==]"
port: "3306"
user: "freedb_Shyam"
password: "![MUleiYInMMhVBu12G4DSLQ==]"
name: "freedb_mahesh"

https:
 port: "8082"
 
autodiscovery:
 id: "19058445"
 
tls:
 keypassword: "![GtWPXnfCuh8Coxj4kZvHfg==]"
 password: "![GtWPXnfCuh8Coxj4kZvHfg==]"
